version: '3.9'
services:
  pwblog-mysql-dev:
    container_name: pwblog-mysql-dev
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pwblog
    volumes:
      - pwblog-mysql-dev:/var/lib/mysql

  pwblog-phpmyadmin-dev:
    container_name: pwblog-phpmyadmin-dev
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - pwblog-mysql-dev
    ports:
      - "8081:80"
    environment:
      PMA_HOST: pwblog-mysql-dev
      MYSQL_ROOT_PASSWORD: pass

  pwblog-wordpress-dev:
    container_name: pwblog-wordpress-dev
    image: wordpress
    depends_on:
      - pwblog-mysql-dev
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: pwblog-mysql-dev
      WORDPRESS_DB_NAME: pwblog
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  pwblog-mysql-dev: